2023-01-11 11:01:24,960 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2023-01-11 11:01:24,971 INFO supervisord started with pid 7
2023-01-11 11:01:25,974 INFO spawned: 'app' with pid 8
2023-01-11 11:01:25,976 INFO spawned: 'nginx' with pid 9
2023-01-11 11:01:27,002 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-01-11 11:01:27,002 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Bottle v0.12.23 server starting up (using WSGIRefServer())...
Listening on http://localhost:5000/
Hit Ctrl-C to quit.

[CTRL] POST /setup
[Time: 11.01.23 11:01:28] [Level: info] id: 76591b0bcd374468
[Time: 11.01.23 11:01:28] [Level: info] coordinator: True
[Time: 11.01.23 11:01:28] [Level: info] clients: ['76591b0bcd374468']
[Time: 11.01.23 11:01:28] [Level: info] state: initial
[Time: 11.01.23 11:01:28] [Level: info] [State: initial] Reading confirguration file...
[Time: 11.01.23 11:01:28] [Level: info] [State: initial] {'data': 'data.csv', 'target_value': 'target', 'sep': ',', 'max_iteration': 10, 'pred': 'pred.csv'}
[Time: 11.01.23 11:01:28] [Level: info] [State: initial] Done reading configuration 10.
[Time: 11.01.23 11:01:28] [Level: info] [State: initial] Reading training data...
127.0.0.1 - - [11/Jan/2023 11:01:28] "POST /api/setup HTTP/1.0" 200 0
/app/states.py:43: FutureWarning: In a future version of pandas all arguments of read_csv except for the argument 'filepath_or_buffer' will be keyword-only.
  df = pd.read_csv(f'{INPUT_DIR}/{input_file}', input_sep)
[Time: 11.01.23 11:01:28] [Level: info] Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 172, in guarded_run
    self.run()
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 187, in run
    transition = self.current_state.run()
  File "/app/states.py", line 43, in run
    df = pd.read_csv(f'{INPUT_DIR}/{input_file}', input_sep)
  File "/root/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/root/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/root/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/root/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/root/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/root/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/root/.local/lib/python3.8/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/input/data.csv'

[CTRL] GET /status
127.0.0.1 - - [11/Jan/2023 11:01:28] "GET /api/status HTTP/1.0" 200 141
