2023-01-11 11:03:03,632 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2023-01-11 11:03:03,633 INFO supervisord started with pid 7
2023-01-11 11:03:04,636 INFO spawned: 'app' with pid 8
2023-01-11 11:03:04,638 INFO spawned: 'nginx' with pid 9
2023-01-11 11:03:05,668 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-01-11 11:03:05,669 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Bottle v0.12.23 server starting up (using WSGIRefServer())...
Listening on http://localhost:5000/
Hit Ctrl-C to quit.

[CTRL] POST /setup
[Time: 11.01.23 11:03:07] [Level: info] id: 862b9e95d63a134e
[Time: 11.01.23 11:03:07] [Level: info] coordinator: True
[Time: 11.01.23 11:03:07] [Level: info] clients: ['862b9e95d63a134e']
[Time: 11.01.23 11:03:07] [Level: info] state: initial
[Time: 11.01.23 11:03:07] [Level: info] [State: initial] Reading confirguration file...
[Time: 11.01.23 11:03:07] [Level: info] [State: initial] {'data': 'data.csv', 'target_value': 'target', 'sep': ',', 'max_iteration': 10, 'pred': 'pred.csv'}
[Time: 11.01.23 11:03:07] [Level: info] [State: initial] Done reading configuration 10.
[Time: 11.01.23 11:03:07] [Level: info] [State: initial] Reading training data...
127.0.0.1 - - [11/Jan/2023 11:03:07] "POST /api/setup HTTP/1.0" 200 0
/app/states.py:43: FutureWarning: In a future version of pandas all arguments of read_csv except for the argument 'filepath_or_buffer' will be keyword-only.
  df = pd.read_csv(f'{INPUT_DIR}/{input_file}', input_sep)
[Time: 11.01.23 11:03:07] [Level: info] Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 172, in guarded_run
    self.run()
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 187, in run
    transition = self.current_state.run()
  File "/app/states.py", line 43, in run
    df = pd.read_csv(f'{INPUT_DIR}/{input_file}', input_sep)
  File "/root/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/root/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/root/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/root/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/root/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/root/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1753, in _make_engine
    return mapping[engine](f, **self.options)
  File "/root/.local/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 79, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 554, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file

[CTRL] GET /status
127.0.0.1 - - [11/Jan/2023 11:03:07] "GET /api/status HTTP/1.0" 200 138
