2023-01-18 10:32:46,593 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2023-01-18 10:32:46,596 INFO supervisord started with pid 7
2023-01-18 10:32:47,598 INFO spawned: 'nginx' with pid 10
2023-01-18 10:32:47,600 INFO spawned: 'app' with pid 11
2023-01-18 10:32:48,642 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-01-18 10:32:48,642 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Bottle v0.12.23 server starting up (using WSGIRefServer())...
Listening on http://localhost:5000/
Hit Ctrl-C to quit.

[CTRL] POST /setup
[Time: 18.01.23 10:32:58] [Level: info] id: 747ed4b22ff26288
[Time: 18.01.23 10:32:58] [Level: info] coordinator: True
[Time: 18.01.23 10:32:58] [Level: info] clients: ['747ed4b22ff26288', '99c287b3c641889b']
[Time: 18.01.23 10:32:58] [Level: info] state: initial
127.0.0.1 - - [18/Jan/2023 10:32:59] "POST /api/setup HTTP/1.0" 200 0
[Time: 18.01.23 10:32:59] [Level: info] [State: initial]  Splits order:
[Time: 18.01.23 10:32:59] [Level: info] [State: initial] Split 0: /mnt/input/data/0
[Time: 18.01.23 10:32:59] [Level: info] [State: initial] Split 1: /mnt/input/data/1
[Time: 18.01.23 10:32:59] [Level: info] [State: initial] Getting sample shape from /mnt/input/data/0/train.npz dataset
[CTRL] GET /status
127.0.0.1 - - [18/Jan/2023 10:32:59] "GET /api/status HTTP/1.0" 200 149
[Time: 18.01.23 10:32:59] [Level: info] Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 172, in guarded_run
    self.run()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 187, in run
    transition = self.current_state.run()
  File "/app/states.py", line 21, in run
    super().run()
  File "/app/utils/pytorch/states.py", line 32, in run
    dl = self.get_dataloader(self.load('input_files')['train'][0])
  File "/app/utils/pytorch/states.py", line 68, in get_dataloader
    dl = dl_class(sample_train_set, **self.config['local_dataset']['detail'])
KeyError: 'detail'

[CTRL] GET /status
127.0.0.1 - - [18/Jan/2023 10:33:02] "GET /api/status HTTP/1.0" 200 132
