2023-01-11 11:00:07,791 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2023-01-11 11:00:07,792 INFO supervisord started with pid 7
2023-01-11 11:00:08,795 INFO spawned: 'app' with pid 8
2023-01-11 11:00:08,800 INFO spawned: 'nginx' with pid 9
2023-01-11 11:00:09,824 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-01-11 11:00:09,825 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Bottle v0.12.23 server starting up (using WSGIRefServer())...
Listening on http://localhost:5000/
Hit Ctrl-C to quit.

[CTRL] POST /setup
[Time: 11.01.23 11:00:11] [Level: info] id: 1e0a8851062aa8b6
[Time: 11.01.23 11:00:11] [Level: info] coordinator: True
[Time: 11.01.23 11:00:11] [Level: info] clients: ['1e0a8851062aa8b6']
[Time: 11.01.23 11:00:11] [Level: info] state: initial
[Time: 11.01.23 11:00:11] [Level: info] [State: initial] Reading confirguration file...
[Time: 11.01.23 11:00:11] [Level: info] [State: initial] {'data': 'data.csv', 'target_value': 'target', 'sep': ',', 'max_iter': 10, 'pred': 'pred.csv'}
127.0.0.1 - - [11/Jan/2023 11:00:11] "POST /api/setup HTTP/1.0" 200 0
[Time: 11.01.23 11:00:11] [Level: info] Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 172, in guarded_run
    self.run()
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 187, in run
    transition = self.current_state.run()
  File "/app/states.py", line 31, in run
    max_iterations = config['max_iteration']
KeyError: 'max_iteration'

[CTRL] GET /status
127.0.0.1 - - [11/Jan/2023 11:00:11] "GET /api/status HTTP/1.0" 200 132
